# Generated by Django 5.1 on 2024-09-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Blog',
        ),
    ]
